name: Github Pages

# By default, runs if you push to main. keeps your deployed app in sync with main branch.
on:
  push:
    branches:
      - main
# to only run when you do a new github release, comment out above part and uncomment the below trigger.
# on:
#   release:
#     types:
#       - published

permissions:
  contents: write # for committing to gh-pages branch.

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4 # repo checkout

      - name: Setup toolchain for wasm
        run: |
          rustup update nightly
          rustup default nightly
          rustup set profile minimal
          rustup target add wasm32-unknown-unknown
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Rust Cache # cache the rust build artefacts
        uses: Swatinem/rust-cache@v2

      - name: Install 
        run: cargo install wasm-pack

      - name: Build first_component
        run: wasm-pack build --target web --release
        working-directory: ./multiple_demo_components/first_component

      - name: Build second_component
        run: wasm-pack build --target web --release
        working-directory: ./multiple_demo_components/second_component

      - name: Build third_component
        run: wasm-pack build --target web --release
        working-directory: ./multiple_demo_components/third_component

      - name: Build fourth_component
        run: wasm-pack build --target web --release
        working-directory: ./multiple_demo_components/fourth_component

      - name: Build fifth_component
        run: wasm-pack build --target web --release
        working-directory: ./multiple_demo_components/fifth_component

      - name: Prepare dist folder
        run: |
          mkdir dist
          mkdir -p dist/first_component/pkg
          mkdir -p dist/second_component/pkg
          mkdir -p dist/third_component/pkg
          mkdir -p dist/fourth_component/pkg
          mkdir -p dist/fifth_component/pkg
          cp multiple_demo_components/first_component/pkg/* dist/first_component/pkg/
          cp multiple_demo_components/second_component/pkg/* dist/second_component/pkg/
          cp multiple_demo_components/third_component/pkg/* dist/third_component/pkg/
          cp multiple_demo_components/fourth_component/pkg/* dist/fourth_component/pkg/
          cp multiple_demo_components/fifth_component/pkg/* dist/fifth_component/pkg/
          cp multiple_demo_components/demo.html dist/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          # this option will not maintain any history of your previous pages deployment
          # set to false if you want all page build to be committed to your gh-pages branch history
          single-commit: true